server:
  port: 8083

spring:

  datasource:
    url: jdbc:postgresql://dev-payment-db:5432/paymentdb
    username: payment
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: dev-kafka:9092