spring:
  application:
    name: payment-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

outbox:
  publisher:
    fixed-delay: 5000

app:
  kafka:
    topics:
      mappings:
        OrderCreatedEvent: order-created
        InventoryReservedEvent: inventory-reserved
        PaymentRequestedEvent: payment-requested
        PaymentCompletedEvent: payment-completed
        PaymentFailedEvent: payment-failed
        InventoryReleaseEvent: inventory-release
        InventoryReleasedEvent: inventory-released

logging:
  level:
    com.mukesh: INFO