server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      acks: all
      retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info